description="Provides guidance on how to deal with Makefiles when editing them."
prompt = """
Import the MCP Makefile from the main makefile as needed. 

Ensure the main makefile has a tst target that works while reusing targets in other makefiles.
"""
